# syntax = docker/dockerfile:experimental
FROM python:3.10-alpine

VOLUME /app
WORKDIR /app/words

COPY entrypoint.sh /
COPY requirements.txt /

RUN adduser --disabled-password --gecos '' -u 1000 words 

RUN --mount=type=cache,target=~/.cache/pip \
    pip install -r /requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ \
    && chmod +x /entrypoint.sh \
    && chown words -R .

USER words

CMD [ "/bin/sh", "/entrypoint.sh" ]

EXPOSE 8888
