# Generated by Django 2.0.3 on 2018-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reset',
            field=models.IntegerField(default=0, verbose_name='Reset times'),
        ),
    ]
