# Generated by Django 2.0.3 on 2018-04-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_review_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='settings_alert_delete_paraphrase',
            field=models.BooleanField(default=True, verbose_name='Settings Alert Delete Paraphrase'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings_alert_delete_review',
            field=models.BooleanField(default=True, verbose_name='Settings Alert Delete Review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings_alert_delete_word',
            field=models.BooleanField(default=True, verbose_name='Settings Alert Delete Word'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings_alert_reset_review',
            field=models.BooleanField(default=True, verbose_name='Settings Alert Reset Review'),
        ),
    ]
