# Generated by Django 3.1.7 on 2021-09-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20181231_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='settings_auto_show_paraphrase',
            field=models.BooleanField(default=True, verbose_name='Settings Auto Show Paraphrase'),
        ),
    ]
