# Generated by Django 3.1.7 on 2024-09-12 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_userprofile_settings_auto_show_paraphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='settings_timedelta',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Settings Time Delta'),
        ),
    ]
